on: [push, pull_request]

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18"]
    name: Node ${{ matrix.node }} Testing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: NPM Install
        run: npm ci

      - name: Lint
        run: npm run-script lint

      - name: NPM Test
        run: npm test

      - name: Build lib
        run: npm run-script build

      - name: NPM Audit
        run: npm audit --production
